export const ERROR_CODES = {
  // Queue errors
  QUEUE_HAS_ACTIVE_TICKETS: 'QUEUE_HAS_ACTIVE_TICKETS',
  QUEUE_NOT_FOUND: 'QUEUE_NOT_FOUND',
  QUEUE_NOT_ACTIVE: 'QUEUE_NOT_ACTIVE',
  QUEUE_IS_FULL: 'QUEUE_IS_FULL',
  
  // Ticket errors
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  NO_TICKETS_AVAILABLE: 'NO_TICKETS_AVAILABLE',
  
  // Tenant errors
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_ALREADY_EXISTS: 'TENANT_ALREADY_EXISTS',
  
  // Agent errors
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_ALREADY_EXISTS: 'AGENT_ALREADY_EXISTS',
  
  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCESS_DENIED: 'ACCESS_DENIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];



