ALTER TYPE "AgentRole" RENAME VALUE 'ATTENDANT' TO 'OPERADOR';
ALTER TYPE "AgentRole" RENAME VALUE 'ADMIN' TO 'ADMINISTRADOR';
ALTER TYPE "AgentRole" RENAME VALUE 'MANAGER' TO 'GERENTE';
ALTER TYPE "AgentRole"
ADD VALUE 'GESTOR';
